global using UserManagement.Application.Queries.Sections.GetById;
global using UserManagement.Application.Queries.Sections.GetAll;
global using UserManagement.Infrastructure.Persistence.Context;
global using UserManagement.Application.Commands.Sections.Add;
global using UserManagement.Application.Dtos.SectionDtos;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using FluentResults;
global using MediatR;
